### ISSUE TITLE
New Version has missing dependencies

### ISSUE THREAD

**Issue by jimmyeao** [poveden/EliteChroma#106]
## Summary

Description: A .NET Core application failed.
Application: EliteChroma.exe
Path: C:\Program Files\EliteChroma\EliteChroma.exe
Message: Error:
  An assembly specified in the application dependencies manifest (EliteChroma.deps.json) was not found:
    package: 'Colore', version: '6.0.0'
    path: 'lib/netstandard2.1/Colore.dll'

## Steps to Reproduce

Launch Elite Chroma

## Expected Behavior

Chroma should Run (Razer Synapse is installed as are .net runtimes (x64)

## Environment

- `EliteChroma` version: v1.12.0
- .NET Core version: 
- C:\Users\jimmy>dotnet --list-runtimes
```
Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Operating System:  Windows 10 21H1

**Comment by poveden** [comment]
Thanks for reporting. Could you check the `%PROGRAMFILES%\EliteChroma` directory and confirm that the `Colore.dll` file is there? The only way I've found to reproduce your issue is to actually remove or delete that file.

**Comment by jimmyeao** [comment]
Looks to be missing..
![image](https://user-images.githubusercontent.com/5197831/120528189-11dacd80-c3d3-11eb-8ac4-0f49ff1d59a4.png)

Doing a repair on the install has put it back there now, thanks for the pointer! It looks like when i installed the new version with the old one present, it didnt replace the file?

**Comment by poveden** [comment]
Glad that it's working for you now. I'll investigate if the EliteChroma installer is doing something weird while updating. Thanks again!
