### ISSUE TITLE
Better Steam installation detection

### ISSUE THREAD

**Issue by poveden** [poveden/EliteChroma#12]
## Summary

Currently, EliteChroma only tries to detect Steam-based game install folders as [documented in the Frontier Support FAQ](https://support.frontier.co.uk/kb/faq.php?id=108), but not if the game is installed under a game library.

## Desired solution

Detect game installations under Steam game libraries.

## Alternative solutions

_Originally posted by @EffortlessFury in https://github.com/poveden/EliteChroma/issues/9#issuecomment-578508184_

A possible solution is [hinted in a Reddit post](https://www.reddit.com/r/learnprogramming/comments/1x0amf/ctrouble_finding_where_a_user_installs_steam/):

> There is a "config.vdf" file inside Steam\config, which mentions the other library paths as BaseInstallFolder_1, BaseInstallFolder_2, etc.
>
> The spec for the vdf format is https://developer.valvesoftware.com/wiki/KeyValues#File_Format but you can just use a regex to find those lines.

**Comment by poveden** [comment]
@EffortlessFury Can you confirm if your Elite installation folder is under one of those library paths (`BaseInstallFolder_#`) in your `config.vdf` file, and if so, what's the actual path? Maybe we can add those to the search list.

**Comment by MrRenter** [comment]
The default steam library is always {Drive letter}\Program Files (x86)\Steam
This cannot be removed. The user can have an additional library on each hard drive and these baseinstallfolders iterate starting at 1 like you have found. You should be able to check the default location and check the config.vdf file for additional install locations.

Here is a gist checking for and pulling the all baseinstall folders.
https://gist.github.com/MrRenter/766a4dc36210e50b54abca7155fcc377

**Comment by poveden** [comment]
Thanks, @MrRenter.

I'll address to you the same question I asked @EffortlessFury before: Can you share with me (if you have Elite:Dangerous installed under a Steam library folder) what's the actual path to it in your setup? I have no trouble parsing the `config.vdf` file, but I'm not willing to do a blind search under all library folders until I find the main .exe file of the game.

**Comment by poveden** [comment]
I've ended up installing E:D through Steam so I could test this feature. [Release 1.2.0](https://github.com/poveden/EliteChroma/releases/tag/v.1.2.0) is up. If anything's wrong, don't hesitate to come back with your feedback.
