### ISSUE TITLE
EDHM UI integration?

### ISSUE THREAD

**Issue by Setzer123** [poveden/EliteChroma#124]
Would it be posable to integrate EliteChroma with EDHM UI so that it pulls the colors of you hud and so forth to apply custom huds colors?

link to EDHM UI if you not sure what I'm talking about.

https://github.com/BlueMystical/EDHM_UI

**Comment by poveden** [comment]
I wasn't aware that EDHM even existed, so this is good to know.

Currently EliteChroma takes the traditional "Elite orange" and the "analysis mode" colors, transforms them using the XML transform matrix (that EDHM successfully avoids), and applies them as background color and some specific key combinations. 

It would be possible to take input from the EDHM configuration. How would you like the configuration to be applied to EliteChroma?

**Comment by Setzer123** [comment]
If you could have it use the hud color that you are using in EDHM and apply this to Elitechroma. I guess instead of the all the keys being orange it changes to what ever the main color of your costume hud and maybe your power level ect. . something alone those lines.

**Comment by poveden** [comment]
@Setzer123 I've added EDHM support in [v.1.16.0](https://github.com/poveden/EliteChroma/releases/tag/v1.16.0). Please have a look at it.
