### ISSUE TITLE
perma-jump animation?

### ISSUE THREAD

**Issue by billhedge** [poveden/EliteChroma#137]
## Summary
Jump animation never goes away.

## Steps to Reproduce

1. Install and run EliteChroma
2. Run ED
3. Jump or enter supercruise

## Expected Behavior
I would expect the jump animation on my devices to cease after the jump is completed.

## Environment

- `EliteChroma` version: 1.16.0
- .NET Core version: 2.1.28 and 2.1.30 (x64 runtime)
- Operating System: Windows 11 (same behavior happened in 10)
- Latest version of Synapse (no updates available)

## Additional Context

I've also uninstalled and cleared out all references to EliteChroma from the file system and registry prior to reinstalling as well as uninstall/reinstall Synapse. The first load appears to be ok until I jump or enter supercruise. Once that happens, the animation sticks which makes it difficult to see the keys that aren't currently being lit by the animation. I think I first noticed this behavior a version or two ago, so it could very well just be something with my setup if no one else is reporting this. Maybe something "stuck" in my journal files?

**Comment by billhedge** [comment]
I just checked it and it works fine with 1.15.0. The part that's sticking with the current version is the initial animation that starts with the countdown, if that helps narrow it down some.

**Comment by Lirlya** [comment]
Same issue here, also works fine on 1.15.0 - (horizon)

**Comment by poveden** [comment]
@billhedge @Lirlya [Version 1.16.1](https://github.com/poveden/EliteChroma/releases/tag/v1.16.1) is up! Please test it and reopen if needed. Thanks!

**Comment by billhedge** [comment]
I just installed and made a couple of supercruise entry/exits and a couple of jumps. Looks good to me! Thanks so much!
