### ISSUE TITLE
Issue Starting Elite Chroma

### ISSUE THREAD

**Issue by kwangoesdk** [poveden/EliteChroma#138]
Si i have installed the Apropiate .NET as it was in the readme file.

I get 3 errors please help me out 

> Application: EliteChroma.exe
> CoreCLR Version: 5.0.1422.5710
> .NET Version: 5.0.14
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentException: An item with the same key has already been added. Key: x157
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
>    at EliteFiles.Internal.D3DXConfig.FromFile(String path) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\D3DXConfig.cs:line 82
>    at EliteFiles.Graphics.EdhmConfig.FromFile(String path) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\EdhmConfig.cs:line 39
>    at EliteFiles.Graphics.EdhmConfigWatcher.<Reload>b__16_0() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\EdhmConfigWatcher.cs:line 123
>    at EliteFiles.Internal.FileOperations.RetryIfFailed[T](Func`1 action, Func`2 test, Int32 retries) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 16
>    at EliteFiles.Internal.FileOperations.RetryIfNull[T](Func`1 action, Int32 retries) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 11
>    at EliteFiles.Graphics.EdhmConfigWatcher.Reload(Boolean reconfigureIncludesWatcher) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\EdhmConfigWatcher.cs:line 122
>    at EliteFiles.Graphics.EdhmConfigWatcher.Start() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\EdhmConfigWatcher.cs:line 62
>    at EliteChroma.Elite.GameStateWatcher.Start() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Elite\GameStateWatcher.cs:line 102
>    at EliteChroma.Core.ChromaController.Start() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 107
>    at EliteChroma.AppContext.CycleChromaController(AppSettings settings) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 181
>    at EliteChroma.AppContext.Start() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 65
>    at EliteChroma.Program.Main() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\Program.cs:line 38

> `Faulting application name: EliteChroma.exe, version: 1.16.0.0, time stamp: 0x619336bf
> Faulting module name: KERNELBASE.dll, version: 10.0.22000.527, time stamp: 0x71a5cb5d
> Exception code: 0xe0434352
> Fault offset: 0x000000000004478c
> Faulting process id: 0x7a90
> Faulting application start time: 0x01d83180fcc02784
> Faulting application path: C:\Program Files\EliteChroma\EliteChroma.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 41e873ec-cc46-41bf-9b1c-8b59b93eaf26
> Faulting package full name: 
> Faulting package-relative application ID: `

> `Fault bucket 1391810758187411741, type 5
> Event Name: CLR20r3
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: MHTR5QV3YIMJ0LMICWAXBVRGOA1H1ECR
> P2: 1.16.0.0
> P3: 619336bf
> P4: System.Private.CoreLib
> P5: 5.0.1422.5710
> P6: 8bbcd4e1
> P7: 1825
> P8: 0
> P9: System.ArgumentException
> P10: 
> 
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b2f3c6a1-cee0-4d75-905b-8319a0b924af.tmp.mdmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a4bef83b-e5e1-465a-962e-24d6c3f5a609.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8514c2ae-499e-4c2e-b10f-38643ac832d9.tmp.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.29a9a9a5-7673-41e2-addc-2d4fef50c2cd.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.14b89912-aa1e-4482-8708-ae3979b5940b.tmp.txt
> 
> These files may be available here:
> \\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MHTR5QV3YIMJ0LMI_3bd18dbf0f176a5affac176a252ee5251bb2b_3a6cc647_5cbd1984-3900-4174-a80f-f8096392e19b
> 
> Analysis symbol: 
> Rechecking for solution: 0
> Report Id: 41e873ec-cc46-41bf-9b1c-8b59b93eaf26
> Report Status: 2147487744
> Hashed bucket: 07aeb9c2b3a186e36350b482ac53e91d
> `

**Comment by kwangoesdk** [comment]
So i guess the software is not being updated

**Comment by poveden** [comment]
Hi @kwangoesdk. Thank you for reporting this. I hope that you appreciate that I develop this tool on my spare time (you know, between family, kids, work), and that sometimes it might take a while for me to answer. Besides, last week it was my birthday. 🎂

From the error, it seems that you have EDHM installed. Can you confirm? If so, could you please share your EDHM config files (probably a .zip file will be the most convenient).

**Comment by poveden** [comment]
@kwangoesdk [Version 1.16.1](https://github.com/poveden/EliteChroma/releases/tag/v1.16.1) is up! Please test it and reopen if needed. Thanks!
