### ISSUE TITLE
Application asks for .NET even though it's been installed

### ISSUE THREAD

**Issue by heltonhm** [poveden/EliteChroma#148]
Fresh installation of Windows 11, prerequisite apps already installed. When attempting to run EliteChroma, it asks for .NET. I made sure to have it installed from the Windows features, but it still doesn't see it.

**Comment by poveden** [comment]
Could you please share more details, like the exact message you are receiving?

You mention that you had it installed from "Windows Features", but .NET 5 (the version required by EliteChroma) is not installed like that, but by downloading and installing it. As per the [README](https://github.com/poveden/EliteChroma#application-requirements):

> ## Application requirements
> - [Microsoft .NET 6.0 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/current/runtime) (_x64_ version)

**Comment by heltonhm** [comment]
Yes, I'd also installed this one, but no luck. The message says "To run this application, you must install .NET. Would you like to download now?" Clicking Yes or No doesn't do anything.

**Comment by poveden** [comment]
Could you please run `dotnet --info` on a command line prompt and share with me the results?

**Comment by heltonhm** [comment]
Sure. That's the command output:

C:\WINDOWS\System32>dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 3.1.23 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by poveden** [comment]
I see the issue now. I expected that EliteChroma 1.16.3, which was built for .NET 5, would run in .NET. Clearly that's not the case.

I've just released [1.17.0](https://github.com/poveden/EliteChroma/releases/tag/v1.17.0), which is built for .NET 6. Install it and let me know how it goes.

**Comment by heltonhm** [comment]
The new version works fine. It fixed the problem. Thanks!
