### ISSUE TITLE
Horizons 4.0 upgrade from 3.8 is not being discovered by EliteChroma

### ISSUE THREAD

**Issue by HardSound1** [poveden/EliteChroma#150]
## Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

So, I install all what I need from guide here, but looks like doesn't work.
## Environment

- `EliteChroma` version: _(e.g. 1.0.0)_               1.17.0
- .NET Core version: _(e.g. 3.0.100)_                .NET 6.0 SDK (v6.0.401)
- Operating System: _(e.g. Windows 10)_         win 11

**Comment by poveden** [comment]
@HardSound1 could you please confirm that EliteChroma is pointing to _all_ the right folders? In particular, if you have both Odyssey and Horizons, they will be in different paths and EliteChroma can only monitor one of them.

Please also tell me whether you have the "Detect when Elite: Dangerous process is running on the foreground" checkbox selected or not.

**Comment by HardSound1** [comment]
could you please confirm that EliteChroma is pointing to all the right folders? In particular, if you have both Odyssey and Horizons, they will be in different paths and EliteChroma can only monitor one of them.
I have only 4.0, not odyssey
UPD! I  found problem after this message a bout cliens!!)) there are 2 folders, 1:"elite-dangerous-64" and 2:"FORC-FDEV-DO-38-IN-40" 
So not only Odysey and Horizonts, also 4.0 are different clients. Can you add description for future?) Thank you for help!

**Comment by poveden** [comment]
Good to hear. It looks like you have installed Horizons via Steam, am I right? Could you please share the _full path_ of those 2 folders you mention, and tell me which one belongs to which version (i.e. 3.8 or 4.0)?

**Comment by HardSound1** [comment]
nope. Its EGS version.
this is 3.8 C:\Program Files\Epic Games\EliteDangerous\Products\elite-dangerous-64
this is 4.0 C:\Program Files\Epic Games\EliteDangerous\Products\FORC-FDEV-DO-38-IN-40
Idk why they put this names of folder

**Comment by HardSound1** [comment]
![image](https://user-images.githubusercontent.com/115062314/194998710-ef65e6e0-e2d0-4668-bf04-d4bb21bf94bc.png)

**Comment by poveden** [comment]
Understood. I'm guessing that, since 3.8 and 4.0 can be both installed at the same time, Frontier devs decided to assign that weird name (actually the product's SKU) to the folder.

I'll include that name so it's shown as an option in the settings window.

Thanks for your help!
