### ISSUE TITLE
EliteChroma (1.17.0) don't start

### ISSUE THREAD

**Issue by SorenKyojin** [poveden/EliteChroma#153]
## Summary

I recently changed my PC and I reinstalled EliteChroma with every dependencies. But It won't start and nothing happen. So I searched on the GitHub page if someone got the same problem, and I reminded that the Event Viewer could help. I opened it and saw an Application Error for EliteChroma, and a .NET Runtime Error.
And also I did a sfc/scannow, Windows found corrupted files and repaired them. So now, please help me what I have to do now.
(Playing Elite without chroma is pretty hard lol)

## Steps to Reproduce

1. Install the last version of EliteChroma on an brand new computer
2. Double Click EliteChroma.exe in its installation folder
3. Check at right of taskbar and check if EliteChroma appears
4. And see nothing happens

## Expected Behavior

- EliteChroma should start normally
- The icon should appears in the right of the taskbar
- The window of first configuration should open first

## Screenshots
I'm french, that's why my english could have mistakes and some elements are french in screenshots.
EliteChroma error:
![image](https://user-images.githubusercontent.com/64634251/198890028-fc756057-5ddb-42ec-961c-74811ef2fbe0.png)

.NET 6.0.8 error:
![image](https://user-images.githubusercontent.com/64634251/198890062-7d353bc9-0db0-4c66-90f2-016c10b67bce.png)

## Environment
System:
- `EliteChroma` version: _1.17.0_
- .NET Core version: _6.0.822.36306_
- Operating System: _Windows 10 (Build 19044.2130)_
Components:
- Processor: AMD RYZEN 5 4500
- RAM: CORSAIR VENGEANCE RGB PRO SL 32 GB (4x8GB) RAM TYPE: DDR4 - 3200 MHz
- Motherboard: AsRock B550 PG RIPTIDE
- Graphic Card: Nvidia GeForce GTX 1650

**Comment by poveden** [comment]
@SorenKyojin Thanks for reporting this. On first impression, it looks like you might have installed the wrong .NET runtime. There are 2 of them:
- The "normal" .NET runtime, and
- [The _desktop_ runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer). <-- This is the one you need.

Please go ahead and install it if you haven't, and let me know how it went.

**Comment by poveden** [comment]
@SorenKyojin Any news?

**Comment by poveden** [comment]
@SorenKyojin I'm closing this after 3 weeks. Please feel free to reopen it if the issue persists.
