### ISSUE TITLE
Yeelight Monitor Bar Support

### ISSUE THREAD

**Issue by Unthred** [poveden/EliteChroma#154]
Hi there,

I have a Yeelight Monitor Bar like this - https://www.amazon.co.uk/YEELIGHT-Monitor-Computer-Backlight-Tunable/dp/B09KGM6K96 
Should it work with Elite Chroma or is it more for keyboards?
I have Razor Synapse, YeelightChromaConnector and EliteChroma installed.
Chroma Connect shows up in the Devices section of Synapse and works if I choose one of the built-in effects. 
Not sure if I have done something wrong or its not supposed to work with it as EliteChroma does not appear in synapse apps page... not sure if it should.

Thanks
Squigs

**Comment by poveden** [comment]
@Unthred EliteChroma supports all devices exposed by Razer Synapse. However, if Yeelight Chroma Connector behaves like Philips Hue (an integration that I have), you must deliberately enable the link on Razer Synapse's Yeelight module.

EliteChroma _should_ appear in Synapse's _Connect_ tab but, for it to appear there you _must_ run EliteChroma at lease once. You should also have the EliteChroma icon sitting there in Windows' task tray.

**Comment by Unthred** [comment]
Thanks for the response! 
So I have Razer Synapse installed and in the devices I have Chroma Connect enabled and Yeelight enabled.
I have run EliteChroma a few times... its running just now however it does now appear in the Apps page.
In EliteChroma I have this as the Game installation folder
```F:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-64``` Is that correct? It was installed through Steam.
The Game options folder and Journal folder seem to be correct to me. They certainly point to folders with stuff in them.

Is there  anything I can do to help debug the issue?

Thanks

**Comment by poveden** [comment]
Do you have any other Razer device (e.g. keyboard, mouse) in your setup? Do they change lighting when EliteChroma and Elite Dangerous are running? If they do, then your Yeelight should change lighting as well.

**Comment by Unthred** [comment]
I wish I knew more about how incompatible different vendors RBG is when I bought these things as my keyboard is hyper-X which is not razor compatible.

**Comment by poveden** [comment]
Please download the following file: [ChromaTest.zip](https://github.com/poveden/EliteChroma/files/9998721/ChromaTest.zip).

Unzip it in any place of your choosing, and run `ChromaTest.exe`. This program will apply colors to any Razer Chroma device available, so you can see whether it's working or not.

Please come back with your results.

**Comment by Unthred** [comment]
Sorry for taking so long to come back to you. I now get Chroma SDK Test showing up in the Apps page of Synapse. Unfortunately, it does nothing to change the colours of the Yeelight Screen Bar Light. 
I have even factory reset the light and then found out it had a firmware update, so I applied that, still nothing.

Is there anything more I can do to help you debug it?

Thanks loads

**Comment by poveden** [comment]
I'm afraid there's nothing I can do from my side. The test program I gave you will apply colors to _all_ Chroma-enabled devices. Make sure that [Yeelight Station](https://www.razer.com/chroma-workshop#--chroma-partners--look--eWVlbGlnaHQ_-_) is installed and correctly configured.

**Comment by Unthred** [comment]
Interesting, I did not have Yeelight station installed and now that I have it installed it does not seem to see the light.
I guess I will have to debug that first and get it working see if anything changes.
I will report back my findings

thanks

**Comment by poveden** [comment]
@Unthred I'm closing this after 3 weeks. Please feel free to reopen if there's anywhing I can help you with.
