### ISSUE TITLE
Crashes when thargoids are attacking

### ISSUE THREAD

**Issue by WFLek** [poveden/EliteChroma#157]
## Summary

Crashes when thargoids are attacking

## Steps to Reproduce

1. Go to system invaded by thargoids

## Expected Behavior

Some cool glitchy effect on keyboard

## Environment

- `EliteChroma` version: 1.17.0
- .NET Core version: 4.8.09032
- Operating System: Windows 11 22H2

**Comment by poveden** [comment]
@WFLek [Version 1.18.0](https://github.com/poveden/EliteChroma/releases/tag/v1.18.0) is out. Try it and tell me how it goes.

**Comment by poveden** [comment]
@WFLek I'm closing this now after 2 weeks. Feel free to reopen if the issue persists.
