### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by CrohmTV** [poveden/EliteChroma#158]
Elite Chroma loads normally, can interact with setting, etc. Upon loading into game instance app crashes.
Was working fine prior to Update 14. No other changes to hardware, peripherals, or apps used.
Have tried repair, uninstall/re-install, including .Net desktop.

**Comment by CrohmTV** [comment]
After finally getting OUT of Thargoid control sys, this is duplicate of previously stated issue. Sorry.

**Comment by poveden** [comment]
Duplicate of #157
