### ISSUE TITLE
EliteChroma silently closes while playing ED

### ISSUE THREAD

**Issue by psolem** [poveden/EliteChroma#162]
## Summary

I don't always have the issue, often time EliteChroma runs fine the entire play session. Other times, like now, it continually closes after a few minutes (or seconds?, or events?). When I open it again it seems to run for a bit then close, usually on an event. I cannot figure out why. Is there error logging happening somewhere that might point me somewhere?
I had thought it maybe involved the journal files, I have 4k hours of journals in the directory. I moved all but the last months into another folder and now EliteChroma closes immediately, i dont even have a chance to open the settings or click on the icon. So the journal or event reading seems to be possibly involved.

## Steps to Reproduce

I am unable to reproduce the issue on demand. 
I cannot find any errors displayed.

## Expected Behavior

EliteChroma does not silently close while playing ED.

## Environment

- `EliteChroma` version: 1.18.0
- .NET Core version: not sure how to get this version info
- Operating System: Windows 10

## Additional Context

Absolutely LOVE this tool and would love to help get this issue resolved. Please let me know how I can help.

**Comment by psolem** [comment]
I ended getting to work again by removing all but the latest journal file then logged into and out of the game a few times to ensure the start/stop events were in that journal. Then i put all the journal files back in place and things have running since. Not sure what happened to cause the issue in the first place

**Comment by poveden** [comment]
Good to hear that! Please come back to me if the issue resurfaces.

**Comment by GrasshopperMan17** [comment]
hey, so i was having the same issue with the app silently shutting down and i did the journal trick and i dont think its come back. havent done extensive tests to make sure, but it seems to have worked. it may be worth it to try and see why this issue comes up so you can possibly patch it in the future

**Comment by GrasshopperMan17** [comment]
> hey, so i was having the same issue with the app silently shutting down and i did the journal trick and i dont think its come back. havent done extensive tests to make sure, but it seems to have worked. it may be worth it to try and see why this issue comes up so you can possibly patch it in the future

UPDATE: it has come back. just shuts down occassionally and have to "jiggle the handle" so to speak to get it to run again
