### ISSUE TITLE
Thargoid Spire Sites Casing Elite Chroma To Crash

### ISSUE THREAD

**Issue by pr1sm47** [poveden/EliteChroma#166]
Chroma behaving normally until approximately 10km from the spire sites. Chroma then crashes to desktop.

Application: EliteChroma.exe v1.18.1
CoreCLR Version: 6.0.2423.51814
.NET Version: 6.0.24
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key 'TGFactory' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
 
Last few lines from journal prior to crash -
{ "timestamp":"2023-11-05T11:40:17Z", "event":"Music", "MusicTrack":"TGFactory" }
{ "timestamp":"2023-11-05T11:42:08Z", "event":"ModuleInfo" }
{ "timestamp":"2023-11-05T11:43:46Z", "event":"FactionKillBond", "Reward":65000, "AwardingFaction":"$faction_PilotsFederation;", "AwardingFaction_Localised":"Pilots' Federation", "VictimFaction":"$faction_Thargoid;", "VictimFaction_Localised":"Thargoids" }

**Comment by poveden** [comment]
Hi @pr1sm47! Sorry for the long delay. I'll apply a fix as soon as I can, and I'll ping you when it's done.

**Comment by poveden** [comment]
[Version 1.18.2](https://github.com/poveden/EliteChroma/releases/tag/v1.18.2) is out. It should fix the issue. Please let me know how it goes.
