### ISSUE TITLE
Elite On different drive

### ISSUE THREAD

**Issue by Ballistic32** [poveden/EliteChroma#27]
The EliteChroma will simply start up then crash on start up as soon as I try to link it to steam. I have Frontier on one Drive and Elite on another, not sure if that would be the problem. I got the game through Steam.

**Comment by poveden** [comment]
@Ballistic32 in order to try to reproduce the issue, I would need from you:

1. What version of EliteChroma do you have, and
2. What are the steps that you followed that led you to the crash (and what happens when it crashes)

**Comment by poveden** [comment]
@Ballistic32 I'm closing this, since I cannot reproduce the issue and you haven't answered me yet. Feel free to reopen at any time.
