### ISSUE TITLE
Invalid game options folder

### ISSUE THREAD

**Issue by Zanteri** [poveden/EliteChroma#51]
Thank you so much for making this, but when I've tried to run it, it forces me to change to the steam game location. But even after I do that it still displays the options folder as "Invalid game options folder". I've checked and the folder exists, but the program does not seem to detect it correctly.

**Comment by mcargille** [comment]
@Zanteri If you resolved your issue, would you mind sharing how in case others encounter the same problem?

**Comment by Zanteri** [comment]
Yes,  I closed the window then played the game a bit, modifying some of the options too. When I exited and tried again it worked.
