### ISSUE TITLE
App Fails to open 

### ISSUE THREAD

**Issue by SquidishXD** [poveden/EliteChroma#64]
The App worked before I had to reinstall windows. Then, it's doesn't work anymore. My Razer devices current color freezes then EliteChroma closes and the RGB continues on.

**Comment by poveden** [comment]
Hi @SquidishXD! Could you please check the Windows Application Event Log just after EliteChroma closes? Look for error entries with .NET Runtime as the event source.

When you say that the device colors get frozen, it it happening during some animation (like when in hyperspace, or being attacked)?

**Comment by poveden** [comment]
@SquidishXD I'm closing this issue after a month of inactivity. Please feel free to reopen anytime if needed.
