### ISSUE TITLE
Rainbow keys

### ISSUE THREAD

**Issue by piebaker** [poveden/EliteChroma#65]
Unsure if this is desired functionality or not, however using an Ornata Chroma most keys and binds light up different colours, it's like staring at a rainbow on my keyboard! 
This drastically reduces the usefulness of this tool personally, as all of my binds are obscured by brighter colours next to them, and any special functionality, like having the landing key pulse is lost amidst the rainbow.

**Comment by poveden** [comment]
@piebaker I'm not sure that I understand your issue. Are the programmed bindings not lighting as expected, or is it that your bindings are very close to each other and their colors bleed into the neighboring keys?

If it's about color bleeding, I think that there's not much I can do, as there is no physical barrier stopping the light of a key to shine into the surrounding keys. Perhaps adjusting the brightness will help? Can you send a picture of how your keyboard looks like?

**Comment by piebaker** [comment]
So, after having a re-look at your example video I've realized that it's all working as it should! (Whoops!) So you can disregard this issue
