### ISSUE TITLE
Bug when trying to launch EliteChroma

### ISSUE THREAD

**Issue by Moreo18** [poveden/EliteChroma#71]
When i start EliteChroma, it opens a window which says : `Object reference not set to an instance of an object`
and in the detail section, it says (sorry, it's in french but it's easy, you can probably understand french words with Google Traduction.

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteChroma.Forms.FrmAppSettings.TvSections_DrawNode(Object sender, DrawTreeNodeEventArgs e) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\Forms\FrmAppSettings.cs:line 197
   at System.Windows.Forms.TreeView.OnDrawNode(DrawTreeNodeEventArgs e)
   at System.Windows.Forms.TreeView.CustomDraw(Message& m)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
System.Private.CoreLib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.700.20.51601
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.CoreLib.dll
----------------------------------------
EliteChroma
    Version de l'assembly : 1.9.0.0
    Version Win32 : 1.9.0.0
    CodeBase : file:///C:/Program%20Files/EliteChroma/EliteChroma.dll
----------------------------------------
System.Runtime
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.dll
----------------------------------------
System.Threading
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.800.120.51303
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Windows.Forms.dll
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 4.0.2.1
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Drawing.Common.dll
----------------------------------------
System.Runtime.InteropServices
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Diagnostics.TraceSource
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.dll
----------------------------------------
System.Runtime.Extensions
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.Extensions.dll
----------------------------------------
System.ComponentModel.Primitives
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Version de l'assembly : 4.2.1.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Drawing.Primitives.dll
----------------------------------------
System.Diagnostics.Debug
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.Debug.dll
----------------------------------------
System.Collections.Specialized
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Specialized.dll
----------------------------------------
EliteChroma.Core.Windows
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Program%20Files/EliteChroma/EliteChroma.Core.Windows.dll
----------------------------------------
EliteChroma.Core
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Program%20Files/EliteChroma/EliteChroma.Core.dll
----------------------------------------
netstandard
    Version de l'assembly : 2.1.0.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/netstandard.dll
----------------------------------------
Colore
    Version de l'assembly : 6.0.0.14
    Version Win32 : 6.0.0.14
    CodeBase : file:///C:/Program%20Files/EliteChroma/Colore.dll
----------------------------------------
Microsoft.Win32.Primitives
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/Microsoft.Win32.Primitives.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l'assembly : 4.0.2.0
    Version Win32 : 4.700.19.56404
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Threading.Thread
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.800.120.51303
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/Accessibility.dll
----------------------------------------
System.Collections.Concurrent
    Version de l'assembly : 4.0.15.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.ResourceManager
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Resources.ResourceManager.dll
----------------------------------------
System.Resources.Extensions
    Version de l'assembly : 4.0.1.0
    Version Win32 : 4.700.20.21406
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Version de l'assembly : 4.2.1.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Memory.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.800.120.51303
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Drawing.dll
----------------------------------------
System.Buffers
    Version de l'assembly : 4.0.5.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Buffers.dll
----------------------------------------
System.ComponentModel
    Version de l'assembly : 4.0.4.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.dll
----------------------------------------
System.Collections.NonGeneric
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.NonGeneric.dll
----------------------------------------
System.Text.Json
    Version de l'assembly : 4.0.1.2
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Text.Json.dll
----------------------------------------
System.IO.FileSystem
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.IO.FileSystem.dll
----------------------------------------
EliteFiles
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Program%20Files/EliteChroma/EliteFiles.dll
----------------------------------------
System.Linq
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Linq.dll
----------------------------------------
Microsoft.Win32.Registry
    Version de l'assembly : 4.1.3.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/Microsoft.Win32.Registry.dll
----------------------------------------
System.Text.RegularExpressions
    Version de l'assembly : 4.2.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Text.RegularExpressions.dll
----------------------------------------
System.Private.Uri
    Version de l'assembly : 4.0.6.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.Uri.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.800.120.51303
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/fr/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Version de l'assembly : 1.4.5.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Version de l'assembly : 1.2.5.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.Text.Encoding.Extensions
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.Tools
    Version de l'assembly : 4.1.2.0
    Version Win32 : 4.700.20.51901
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.Tools.dll
----------------------------------------

************** Débogage JIT **************

**Comment by Moreo18** [comment]
just tell me if you need more details

**Comment by poveden** [comment]
Hi @Moreo18! Yes, I have a couple of questions: Is it the first time that you are running EliteChroma? If it is, did you see any other message previous to the error?

**Comment by poveden** [comment]
@Moreo18 nevermind. I've been able to reproduce your issue. I'll post a fix as soon as possible. Thank you for reporting this!

**Comment by Moreo18** [comment]
Nice, have a good day

**Comment by poveden** [comment]
@Moreo18 [Version 1.9.1](https://github.com/poveden/EliteChroma/releases/tag/v1.9.1) is live. Please install it and tell me how it goes.

**Comment by Moreo18** [comment]
it works perfectly, i hope there will be more effect, have a good day
