### ISSUE TITLE
App silently crashes on first and all runs

### ISSUE THREAD

**Issue by EffortlessFury** [poveden/EliteChroma#9]
## Summary

The application crashes so quickly that it doesn't even appear to run.

## Additional Context

I ran the source code and the issue appears to be a lack of default settings. Because the initialized AppContext object has no defaults, the values are null, which can not be passed into the DirectoryInfo initializer at GameInstallFolder:cs:45.

This appears to happen if the AppContext.GetPossibleGameInstallFolders() function fails to find any path whatsoever.

**Comment by EffortlessFury** [comment]
Your code isn't accounting for Steam installations.

https://www.reddit.com/r/learnprogramming/comments/1x0amf/ctrouble_finding_where_a_user_installs_steam/

**Comment by EffortlessFury** [comment]
Easiest fix is probably to provide a default path in place of nothing, even if that path is completely wrong, seeing as you have already provided a means to specify the install directory manually if it does not "exist."

**Comment by EffortlessFury** [comment]
No new tests introduced yet; the entire AppContext file is uncovered. I recommend making the initial validation section of ValidateFolders() a separate static and creating a test against that. Let me know if that's ok and I'll create the test myself if you'd like.

**Comment by poveden** [comment]
Nice catch, @EffortlessFury!

> Easiest fix is probably to provide a default path in place of nothing, even if that path is completely wrong, seeing as you have already provided a means to specify the install directory manually if it is not locatable.

I'll follow your advice but instead I'll go with the 1st entry from `AppContext.GetPossibleGameInstallFolders()`. In consequence, I'll close #10, but thanks anyway!

> Your code isn't accounting for Steam installations.

My code does take into account Steam, but indeed I use only what's [stated by Frontier Support](https://support.frontier.co.uk/kb/faq.php?id=108). I've followed your Reddit link, and I could use some support from you: Can you confirm if your Elite installation folder is under one of those library paths (`BaseInstallFolder_#`) in your `config.vdf` file, and if so, what's the actual path? Maybe we can add those to the search list.

> No new tests introduced yet; the entire AppContext file is uncovered. I recommend making the initial validation section of ValidateFolders() a separate static and creating a test against that. Let me know if that's ok and I'll create the test myself if you'd like.

What kind of test you have in mind? I'm very curious to see how you can test that `MessageBox.Show()` without resorting to some weird mocking implementation. Please do share your thoughts.

**Comment by poveden** [comment]
I'm closing this issue, as #11 has been merged. Moved the rest of the conversation to #12 and #15.
